package main

import (
	_ "gin-base/docs" //docs is generated by Swag CLI.
	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

func main() {
	r := gin.Default()
	//Configure CORS
	config := cors.DefaultConfig()
	config.AllowOrigins = []string{"http://127.0.0.1:8092"} // or use config.AllowAllOrigins = true to allow all origins
	r.Use(cors.New(config))
	//Swagger 2.0 Meta Information
	url := ginSwagger.URL("http://localhost:8092/swagger/doc.json")
	//The url pointing to API definition
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))


	//listen and serve on 0.0.0.0:8080 (for windows "localhost:8080")
	r.Run("127.0.0.1:8092")
}
