package main

import (
	"gin-base/config"
	_ "gin-base/docs" //docs is generated by Swag CLI.
	"gin-base/internal/database"
	"gin-base/internal/routers"
	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)


func main() {
	r := gin.Default()
	//加载配置
	config.LoadConfig("conf/app.ini")
	//初始化数据库
	database.Init()
	// 设置CORS
	setupCORS(r)
	//Swagger init
	setupSwagger(r)
	//初始化路由
	routers.SetupRouter(r)
	//run server
	r.Run(":" + config.Config.App.Port)
}


func setupCORS(r *gin.Engine) {
	r.Use(cors.New(cors.Config{
		AllowOrigins: []string{"*"},
		AllowMethods: []string{"GET", "POST", "PUT", "PATCH", "DELETE", "HEAD"},
		AllowHeaders: []string{"Origin", "Content-Length", "Content-Type"},
	}))
}

func setupSwagger(r *gin.Engine) {
	url := ginSwagger.URL("http://localhost:8091/swagger/doc.json") // Swagger JSON的URL
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))
}

