package main

import (
	"gin-base/config"
	_ "gin-base/docs" //docs is generated by Swag CLI.
	cors2 "gin-base/internal/cors"
	"gin-base/internal/model"
	"gin-base/internal/routers"
	"gin-base/internal/swagger"
	"github.com/gin-gonic/gin"
)

func init() {
	//加载配置
	config.LoadConfig("conf/app.ini")
	//初始化数据库
	model.Init()
}

func main() {
	// 强制日志颜色化
	gin.ForceConsoleColor()

	// 设置debug/release
	gin.SetMode(config.Config.App.RunMode)

	server := gin.Default()
	//全局中间件 Logger 中间件将日志写入 gin.DefaultWriter
	server.Use(gin.Logger())

	//Recovery 中间件会 recover 任何 panic。如果有 panic 的话，会写入 500。
	server.Use(gin.Recovery())

	// 设置CORS
	cors2.SetupCors(server)

	//Swagger init
	swagger.SetupSwagger(server)

	//初始化路由
	routers.SetupRouter(server)

	//run server
	server.Run(":" + config.Config.App.Port)
}
