info:
  contact: {}
  description: This is a sample Server pets
  title: gin-base api doc
  version: v-0.0.1
paths:
  /articles/add:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 标题
        in: formData
        name: title
        required: true
        type: string
      - description: 内容
        in: formData
        name: content
        required: true
        type: string
      - description: 状态
        in: formData
        name: status
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 添加文章
      tags:
      - Article
  /articles/delete:
    delete:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: Article ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 删除文章
      tags:
      - Article
  /articles/info:
    get:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: Article ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 文章详情
      tags:
      - Article
  /articles/list:
    get:
      parameters:
      - description: keyword
        in: query
        name: keyword
        type: string
      - description: page
        in: query
        name: page
        type: integer
      - description: page_size
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 文章列表
      tags:
      - Article
  /articles/update:
    put:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: Article ID
        in: path
        name: id
        required: true
        type: integer
      - description: 标题
        in: formData
        name: title
        required: true
        type: string
      - description: 内容
        in: formData
        name: content
        required: true
        type: string
      - description: 状态
        in: formData
        name: status
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 更新文章
      tags:
      - Article
  /auth/login:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 登陆
      tags:
      - Auth
  /auth/logout:
    get:
      responses: {}
      summary: 退出登陆
      tags:
      - Auth
  /category/add:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 分类名称
        in: formData
        name: name
        required: true
        type: string
      - description: 状态
        in: formData
        name: status
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 添加分类
      tags:
      - Category
  /category/delete:
    delete:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 分类ID
        in: formData
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 删除分类
      tags:
      - Category
  /category/info:
    get:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 分类详情
      tags:
      - Category
  /category/list:
    get:
      parameters:
      - description: keyword
        in: query
        name: keyword
        type: string
      - description: page
        in: query
        name: page
        type: integer
      - description: page_size
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 分类列表
      tags:
      - Category
  /category/tree:
    get:
      consumes:
      - application/x-www-form-urlencoded
      produces:
      - application/json
      responses: {}
      summary: 获取栏目树形分类
      tags:
      - Category
  /category/update:
    put:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 分类ID
        in: formData
        name: id
        required: true
        type: integer
      - description: 分类名称
        in: formData
        name: name
        required: true
        type: string
      - description: 状态
        in: formData
        name: status
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 更新分类
      tags:
      - Category
  /manager/add:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 用户名
        in: formData
        name: name
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      - description: 状态
        in: formData
        name: status
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 添加管理员
      tags:
      - Manage
  /manager/delete:
    delete:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: Manager ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 删除管理员
      tags:
      - Manage
  /manager/list:
    get:
      parameters:
      - description: keyword
        in: query
        name: keyword
        type: string
      - description: page
        in: query
        name: page
        type: integer
      - description: page_size
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 管理员列表
      tags:
      - Manage
  /manager/update:
    put:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: Manager ID
        in: path
        name: id
        required: true
        type: integer
      - description: 用户名
        in: formData
        name: name
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      - description: 状态
        in: formData
        name: status
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 更新管理员
      tags:
      - Manage
  /menu/add:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: name
        in: query
        name: name
        required: true
        type: string
      - description: title
        in: query
        name: title
        required: true
        type: string
      - description: pid
        in: query
        name: pid
        required: true
        type: integer
      - description: icon
        in: query
        name: icon
        required: true
        type: string
      - description: path
        in: query
        name: path
        required: true
        type: string
      - description: status
        in: query
        name: status
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 添加菜单
      tags:
      - Menu
  /menu/delete:
    delete:
      consumes:
      - application/x-www-form-urlencoded
      responses: {}
      summary: 删除菜单
      tags:
      - Menu
  /menu/list:
    get:
      parameters:
      - description: name
        in: query
        name: name
        type: string
      - description: page
        in: query
        name: page
        type: integer
      - description: page_size
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 菜单列表
      tags:
      - Menu
  /menu/tree:
    get:
      responses: {}
      summary: 获取菜单树
      tags:
      - Menu
  /menu/update:
    put:
      consumes:
      - application/x-www-form-urlencoded
      responses: {}
      summary: 更新菜单
      tags:
      - Menu
  /nav/add:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: name
        in: query
        name: name
        required: true
        type: string
      - description: parentId
        in: query
        name: parentId
        required: true
        type: string
      - description: url
        in: query
        name: url
        required: true
        type: string
      - description: status
        in: query
        name: status
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 添加导航
      tags:
      - Navigation
  /nav/delete:
    delete:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: ID
        in: formData
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 删除导航
      tags:
      - Navigation
  /nav/list:
    get:
      parameters:
      - description: name
        in: query
        name: name
        type: string
      - description: page
        in: query
        name: page
        type: integer
      - description: page_size
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 获取导航列表
      tags:
      - Navigation
  /nav/update:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: name
        in: query
        name: name
        required: true
        type: string
      - description: parentId
        in: query
        name: parentId
        required: true
        type: string
      - description: url
        in: query
        name: url
        required: true
        type: string
      - description: status
        in: query
        name: status
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 更新导航
      tags:
      - Navigation
  /system/add:
    post:
      parameters:
      - description: sys_name
        in: formData
        name: sys_name
        required: true
        type: string
      - description: sys_value
        in: formData
        name: sys_value
        required: true
        type: string
      - description: sys_type
        in: formData
        name: sys_type
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 添加系统配置
      tags:
      - System
  /system/delete:
    delete:
      parameters:
      - description: id
        in: formData
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 删除系统配置
      tags:
      - System
  /system/list:
    get:
      parameters:
      - description: sys_name
        in: query
        name: sys_name
        type: string
      - description: page
        in: query
        name: page
        type: integer
      - description: page_size
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 获取系统配置列表
      tags:
      - System
  /system/update:
    put:
      parameters:
      - description: id
        in: formData
        name: id
        required: true
        type: integer
      - description: sys_name
        in: formData
        name: sys_name
        required: true
        type: string
      - description: sys_value
        in: formData
        name: sys_value
        required: true
        type: string
      - description: sys_type
        in: formData
        name: sys_type
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 更新系统配置
      tags:
      - System
  /users/list:
    get:
      parameters:
      - description: name
        in: query
        name: name
        type: string
      - description: page
        in: query
        name: page
        type: integer
      - description: page_size
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 用户列表
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
