info:
  contact: {}
  description: This is a sample Server pets
  title: gin-base api doc
  version: v-0.0.1
paths:
  /articles/add:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 标题
        in: formData
        name: title
        required: true
        type: string
      - description: 内容
        in: formData
        name: content
        required: true
        type: string
      - description: 状态
        in: formData
        name: status
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 添加文章
      tags:
      - Article
  /articles/delete:
    delete:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: Article ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 删除文章
      tags:
      - Article
  /articles/info:
    get:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: Article ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 文章详情
      tags:
      - Article
  /articles/list:
    get:
      parameters:
      - description: keyword
        in: query
        name: keyword
        type: string
      - description: page
        in: query
        name: page
        type: integer
      - description: page_size
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 文章列表
      tags:
      - Article
  /articles/update:
    put:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: Article ID
        in: path
        name: id
        required: true
        type: integer
      - description: 标题
        in: formData
        name: title
        required: true
        type: string
      - description: 内容
        in: formData
        name: content
        required: true
        type: string
      - description: 状态
        in: formData
        name: status
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 更新文章
      tags:
      - Article
  /auth/login:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 登陆
      tags:
      - Auth
  /auth/logout:
    get:
      responses: {}
      summary: 退出登陆
      tags:
      - Auth
  /manager/add:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 用户名
        in: formData
        name: name
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      - description: 状态
        in: formData
        name: status
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 添加管理员
      tags:
      - Manage
  /manager/delete:
    delete:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: Manager ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 删除管理员
      tags:
      - Manage
  /manager/list:
    get:
      parameters:
      - description: keyword
        in: query
        name: keyword
        type: string
      - description: page
        in: query
        name: page
        type: integer
      - description: page_size
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 管理员列表
      tags:
      - Manage
  /manager/update:
    put:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: Manager ID
        in: path
        name: id
        required: true
        type: integer
      - description: 用户名
        in: formData
        name: name
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      - description: 状态
        in: formData
        name: status
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 更新管理员
      tags:
      - Manage
  /users/list:
    get:
      parameters:
      - description: name
        in: query
        name: name
        type: string
      - description: page
        in: query
        name: page
        type: integer
      - description: page_size
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 用户列表
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
