info:
  contact: {}
  description: This is a sample Server pets
  title: gin-base api doc
  version: v-0.0.1
paths:
  /auth/login:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 登陆
      tags:
      - Auth
  /auth/logout:
    get:
      responses: {}
      summary: 退出登陆
      tags:
      - Auth
  /manager/list:
    get:
      parameters:
      - description: keyword
        in: query
        name: keyword
        type: string
      - description: page
        in: query
        name: page
        type: integer
      - description: page_size
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Get Manager List
      tags:
      - Manage
  /users/list:
    get:
      parameters:
      - description: name
        in: query
        name: name
        type: string
      - description: page
        in: query
        name: page
        type: integer
      - description: page_size
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Get User List
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
